services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env  
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: $BACKEND_IMAGE:${TAG}   
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env  
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    image: $FRONTEND_IMAGE:${TAG}  
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env 
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
