name: full-stack-docker-kubernetes-workflow
    

on:
  push:
    branches: ci-cd 
    paths:
      - .github/workflows/docker-build-push-deploy-workflow.yml

  pull_request:
    branches: none # [ main ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  FRONTEND_IMAGE: frontend-simple-app
  BACKEND_IMAGE: backend-simple-app
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend Build & Push
      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend  # Frontend directory containing Dockerfiles
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}

      # Backend Build & Push
      - name: Build and push Backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend  # Backend directory containing Docke
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}
  
  deploy:
    needs: build-push-docker
    runs-on: self-hosted

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Update Kubernetes manifests
        run: |
          cd manifest_files
          # Replace placeholders with actual values
          sed -i "s|__REGISTRY__|$REGISTRY|g" *.yaml
          sed -i "s|__DOCKER_USERNAME__|$DOCKER_USERNAME|g" *.yaml
          sed -i "s|__FRONTEND_IMAGE__|$FRONTEND_IMAGE|g" *.yaml
          sed -i "s|__BACKEND_IMAGE__|$BACKEND_IMAGE|g" *.yaml
          sed -i "s|__IMAGE_TAG__|$IMAGE_TAG|g" *.yaml

      - name: Deploy to Kubernetes
        working-directory: manifest_files
        run: |
          kubectl apply -f .
          
      - name: Verify deployments
        run: |
          kubectl get deployments -o wide
          echo "Frontend image used:" 
          kubectl get deployment frontend-deployment -o jsonpath='{.spec.template.spec.containers[0].image}'
          echo "Backend image used:"
          kubectl get deployment backend-deployment -o jsonpath='{.spec.template.spec.containers[0].image}'
  