name: docker-build-workflow

on:
  push:
    branches: ci-cd 
    paths:
      - .github/workflows/docker-build-workflow.yml

  pull_request:
    branches: none # [ main ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build-container:

    runs-on: ubuntu-latest
    
    steps:
      - name: Get code
        uses: actions/checkout@v3
    
      - name: Build the Docker frontend image
        working-directory: frontend
        run: docker build . --file Dockerfile --tag my-frontend:$(date +%s)

      - name: Build the Docker backend image
        working-directory: backend
        run: docker build . --file Dockerfile --tag my-backend:$(date +%s)
