
name: Main CI/CD Pipeline

on:
  push:
    branches: [ci-cd]
    paths: .github/workflows/reuseable-main-workflow.yml
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  FRONTEND_IMAGE: frontend-simple-app
  BACKEND_IMAGE: backend-simple-app
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  security-scan:
    uses: ./.github/workflows/reuseable-codeql-workflow.yml
    secrets: inherit

  container-scan:
    uses: ./.github/workflows/reuseable-trivy-workflow.yml
    secrets: inherit
    with:
      registry: ${{ .env.REGISTRY }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      frontend_image: ${{ FRONTEND_IMAGE }}
      backend_image: ${{ BACKEND_IMAGE }}
      image_tag: ${{ IMAGE_TAG}}
    needs: security-scan

  build-deploy:
    uses: ./.github/workflows/reuseable-build-deploy-workflow.yml
    secrets: inherit
    with:
      registry: ${{ .env.REGISTRY }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      frontend_image: ${{ FRONTEND_IMAGE }}
      backend_image: ${{ BACKEND_IMAGE }}
      image_tag: ${{ IMAGE_TAG}}
    needs: container-scan