
name: Main CI/CD Pipeline

on:
  push:
    branches: [ci-cd]
    paths: .github/workflows/reuseable-main-workflow.yml
  workflow_dispatch:

env:
  registry: docker.io
  frontend_image: frontend-simple-app
  backend_image: backend-simple-app
  image_tag: '1.0.${{ github.run_number }}'


jobs:
  security-scan:
    uses: ./.github/workflows/reuseable-codeql-workflow.yml
    secrets: inherit
    permissions:
      actions: read
      security-events: write
      contents: read
      packages: read

  container-scan:
    uses: ./.github/workflows/reuseable-trivy-workflow.yml
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      registry: ${{ env.registry }}
      frontend_image: ${{ env.frontend_image }}
      backend_image: ${{ env.backend_image }}
      image_tag: ${{ env.image_tag }}
    needs: security-scan

  build-deploy:
    uses: ./.github/workflows/reuseable-build-deploy-workflow.yml
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      registry: ${{ env.registry }}
      frontend_image: ${{ env.frontend_image }}
      backend_image: ${{ env.backend_image }}
      image_tag: ${{ env.image_tag }}
    needs: container-scan