# .github/workflows/trivy-workflow.yml
name: Trivy Security Scan

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      frontend_image:
        required: true
        type: string
      backend_image:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      registry: ${{ inputs.registry }}
      docker_username: ${{ inputs.docker_username }}
      frontend_image: ${{ inputs.frontend_image }}
      backend_image: ${{ inputs.backend_image }}
      image_tag: ${{ inputs.image_tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ inputs.secrets.DOCKER_USERNAME }}
          password: ${{ inputs.secrets.DOCKER_PASSWORD }}

      # Frontend Build & Scan
      - name: Build Frontend Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: false  # Build but don't push for scanning
          load: true
          tags: frontend:${{ github.sha }}

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend:${{ github.sha }}'
          format: 'sarif'
          output: 'frontend-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Backend Build & Scan
      - name: Build Backend Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: false
          load: true
          tags: backend:${{ github.sha }}

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend:${{ github.sha }}'
          format: 'sarif'
          output: 'backend-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Save scan history
      - name: Save Trivy scan results
        if: always()
        run: |
          mkdir -p trivy-results
          echo "Scan completed on $(date)" >> trivy-results/scan-history.txt
          echo "Frontend Image: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}" >> trivy-results/scan-history.txt
          echo "Backend Image: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}" >> trivy-results/scan-history.txt
          cat frontend-trivy-results.txt >> trivy-results/scan-history.txt
          cat backend-trivy-results.txt >> trivy-results/scan-history.txt

      # Upload scan results as artifacts
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-scan-results
          path: trivy-results/